name: gafgaff
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  # For making request to firestore database
  cloud_firestore: ^0.12.9

  # For handling permissions
  # permission_handler: ^4.1.0
  # For handling authentication via firebase
  firebase_auth: 0.11.1+7
  firebase_messaging: ^6.0.10

  # For handling google sign in
  google_sign_in: ^4.0.2

  # Shimmer effect library
  shimmer: ^1.0.1

  # Gradient app bar
  gradient_app_bar: ^0.1.3

  # Emojies
  emoji_picker: ^0.1.0

  # image_picker
  image_picker: ^0.6.3+1

  # path provider
  path_provider: ^1.6.0

  # firebase storage
  firebase_storage: ^3.1.1

  # provider
  provider: ^4.0.3

  # cached network image
  cached_network_image: ^2.0.0

  # agora rtc engine
  agora_rtc_engine: ^1.0.8

  # permission handler
  permission_handler: null
  contacts_service: null

  # local storage
  hive: ^1.4.1+1
  sqflite: ^1.3.0

  # intl
  intl: ^0.16.1
  connectivity: ^0.4.9+2
  share: ^0.6.5
  shared_preferences: ^0.5.10
  flutter_linkify: ^3.1.3
  url_launcher: ^5.5.2
  image_downloader: ^0.20.0
  video_player: ^0.10.12+2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/profile-pics/
    - assets/images/
    - assets/images/emojis/child/

  # To add assets to your application, add an assets section, like this:
  # assets:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 300
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

